name: CI

on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: moneymeets/action-setup-python-poetry@master

      - uses: moneymeets/moneymeets-composite-actions/lint-python@master

      - run: poetry run python -m pytest --cov --cov-fail-under=85
